### ISSUE TITLE
Can you give me the libri_train_preprocess.json file? Thank you very much!

### ISSUE THREAD

**Issue by Forestmumu** [dimitriStoidis/GenGAN#2]

**Comment by dimitriStoidis** [comment]
Thank you for your message.

Regarding your question about the `libri_train_preprocess.json` file, please note that the absolute paths to our audio files are internal and cannot be shared. However, you can reproduce the file by providing the absolute path to your audio files on your system, along with the start and end times of each utterance.

For example, the following format can be used:
`["path-to-file/LibriSpeech/train/wav/446-123502-0026.wav", 0.0, 13.58]`

You can follow the same process to create the `libri_test_preprocess.json` file for the test set.

Please let us know if you have any further questions or concerns.
